[{
  "comments": [{
    "author": {
      "login": "shivaram"
    },
    "body": "Why will this generate an error ?",
    "commit": "ddf8caa071ee98c64ed57f195f52932e9fc35a5c",
    "createdAt": "2017-05-01T05:16:55Z",
    "diffHunk": "@@ -61,6 +61,7 @@ test_that(\"read.stream, write.stream, awaitTermination, stopQuery\", {\n \n   stopQuery(q)\n   expect_true(awaitTermination(q, 1))\n+  expect_error(awaitTermination(q), NA)",
    "line": 4
  }, {
    "author": {
      "login": "felixcheung"
    },
    "body": "`NA` means expects no error ;)\r\nyea, it's not very intuitive. There is no return value in this case, so just checking to make sure it doesn't throw an error",
    "commit": "ddf8caa071ee98c64ed57f195f52932e9fc35a5c",
    "createdAt": "2017-05-01T05:36:02Z",
    "diffHunk": "@@ -61,6 +61,7 @@ test_that(\"read.stream, write.stream, awaitTermination, stopQuery\", {\n \n   stopQuery(q)\n   expect_true(awaitTermination(q, 1))\n+  expect_error(awaitTermination(q), NA)",
    "line": 4
  }],
  "prId": 17815
}]