[{
  "comments": [{
    "author": {
      "login": "vanzin"
    },
    "body": "This is what caused the error, coupled with the call to `initializeResourceTypes` below. The request object would have a different internal view of resources and would throw an unexpected exception later in the test.",
    "commit": "5642f3aa5de1d069ad7e1741213a0be81f2518b6",
    "createdAt": "2018-10-16T21:09:42Z",
    "diffHunk": "@@ -163,52 +134,6 @@ class ResourceRequestHelperSuite extends SparkFunSuite with Matchers {\n       include(NEW_CONFIG_DRIVER_MEMORY))\n   }\n \n-  private def verifySetResourceRequestsSuccessful(\n-      definedResourceTypes: List[String],\n-      resourceRequests: Map[String, String],\n-      expectedResources: Map[String, ResourceInformation]): Unit = {\n-    assume(ResourceRequestHelper.isYarnResourceTypesAvailable())\n-    ResourceRequestTestHelper.initializeResourceTypes(definedResourceTypes)\n-\n-    val resource = createResource()\n-    ResourceRequestHelper.setResourceRequests(resourceRequests, resource)\n-\n-    expectedResources.foreach { case (name, ri) =>\n-      val resourceInfo = ResourceRequestTestHelper.getResourceInformationByName(resource, name)\n-      assert(resourceInfo === ri)\n-    }\n-  }\n-\n-  private def verifySetResourceRequestsException(\n-      definedResourceTypes: List[String],\n-      resourceRequests: Map[String, String],\n-      message: String): Unit = {\n-    val resource = createResource()\n-    verifySetResourceRequestsException(definedResourceTypes, resource, resourceRequests, message)\n-  }\n-\n-  private def verifySetResourceRequestsException(\n-      definedResourceTypes: List[String],\n-      resource: Resource,",
    "line": 188
  }],
  "prId": 22751
}]