[{
  "comments": [{
    "author": {
      "login": "WeichenXu123"
    },
    "body": "`vector1 === vector2`\r\nand the error message looks strange. ==> s\"scaled value $vector2 do not equal expected value \"$vector1\" ?",
    "commit": "592670c90975d904605864f3168eff00c2befa5d",
    "createdAt": "2018-04-03T10:34:25Z",
    "diffHunk": "@@ -45,9 +44,9 @@ class MaxAbsScalerSuite extends SparkFunSuite with MLlibTestSparkContext with De\n       .setOutputCol(\"scaled\")\n \n     val model = scaler.fit(df)\n-    model.transform(df).select(\"expected\", \"scaled\").collect()\n-      .foreach { case Row(vector1: Vector, vector2: Vector) =>\n-      assert(vector1.equals(vector2), s\"MaxAbsScaler ut error: $vector2 should be $vector1\")\n+    testTransformer[(Vector, Vector)](df, model, \"expected\", \"scaled\") {\n+      case Row(vector1: Vector, vector2: Vector) =>\n+        assert(vector1.equals(vector2), s\"MaxAbsScaler error: $vector2 should be $vector1\")"
  }],
  "prId": 20964
}]