[{
  "comments": [{
    "author": {
      "login": "rxin"
    },
    "body": "does send ever throw an exception? what happens to that thread?\n",
    "commit": "287e9f84811205a0f24699ac18632c354bed59c7",
    "createdAt": "2015-03-31T01:08:01Z",
    "diffHunk": "@@ -87,9 +86,15 @@ private[spark] class LocalActor(\n     }\n     if (tasks.isEmpty && scheduler.activeTaskSets.nonEmpty) {\n       // Try to reviveOffer after 1 second, because scheduler may wait for locality timeout\n-      context.system.scheduler.scheduleOnce(1000 millis, self, ReviveOffers)\n+      reviveThread.schedule(new Runnable {\n+        override def run(): Unit = self.send(ReviveOffers)"
  }],
  "prId": 5268
}]